FROM nginx:alpine

# Copy Angular build files to Nginx's serving directory
COPY dist/calc-pro/browser/* /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]