FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# Copy Angular build files to Nginx's serving directory
COPY dist/calc-pro/browser/* /usr/share/nginx/html

# Copy custom Nginx configuration
COPY default /etc/nginx/sites-enabled

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]